name: Main CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  nasa_api_key: ${{ secrets.NASA_API_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build the app
        run: ./gradlew assembleDebug --stacktrace

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace
